#!/usr/bin/env python
# -*- coding: utf-8 -*-


"""Convenience wrapper for running bootstrap directly from source tree."""


import sys
import os

HERE = os.path.realpath(os.path.dirname(__file__))
sys.path.append(os.path.join(HERE, "src"))

from minos.minos import main


if __name__ == '__main__':
    main()
